version: "3"
services:
  api:
    image: ezgen_api
    build: ./api
    command: python3 EzGen.py
    ports:
      - 8015:8015
    network_mode: host
    container_name: ezgen_api
  telegram:
    image: ezgen_telegram
    depends_on:
      - api
    build: ./telegram
    command: python3 EzGenTG.py
    container_name: ezgen_telegram
  